Add more mappings
TextileMC/yarrn pull request #15
Opened 2022-03-26 00:57 UTC by tl0x

Mainly block and rendering stuff, take a look.

2022-03-26 23:05 UTC, sschr15 requested changes
pls fix the english language or the one method's name

2022-03-26 23:05 UTC, sschr15 commented on mappings/net/minecraft/entity/Entity.mapping
> +	METHOD method_339 recieveDamage (I)V
```suggestion
	METHOD method_339 receiveDamage (I)V
```
I before E except for all the exceptions

2022-03-28 13:47 UTC, arthurbambou approved these changes

2022-03-28 20:42 UTC, arthurbambou approved these changes

2022-03-30 13:59 UTC, sschr15 approved these changes

2022-03-30 23:30 UTC, merged