Did another pass on the block package
TextileMC/yarrn pull request #16
Opened 2022-03-26 22:14 UTC by amusingimpala75

Went through the blocks package and did some more mapping

2022-03-26 23:10 UTC, sschr15 reviewed
unnecessary comments because of proguard should maybe get disappeared

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Dirt.mapping
> +	COMMENT @param textureIndex Index is ignored by the parameter
cool comments but eh

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Door.mapping
> +	COMMENT @param id Id is ignored by the constructor
same as dirt: great comment but eh

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Fire.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Ladder.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Leaves.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Log.mapping
> +	COMMENT @param id Id is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Obsidian.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Rail.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
same as above

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/SignBlock.mapping
> +	COMMENT @param id Id is ignored by the constructor
here too

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Sponge.mapping
> +	COMMENT @param id Id is ignored by the constructor
and here

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/StoneSlab.mapping
> +	COMMENT @param id Id is ignored by the constructor
here as well

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/TNT.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
also here

2022-03-26 23:10 UTC, sschr15 commented on mappings/net/minecraft/block/Torch.mapping
> +	COMMENT @param textureIndex Texture Index is ignored by the constructor
here as well part 2

2022-03-30 23:32 UTC, sschr15 requested changes
PR blocked until this can be figured out
what is better name for what the method does and where it's called

![image](https://user-images.githubusercontent.com/15277819/160947457-b6d4708a-06fb-4176-8ac9-9ee87b90c9e4.png)

2022-03-31 02:54 UTC, amusingimpala75 commented
Well, it makes sense to call it can connect towards, because sometimes it can connect towards an air block which has a rail above it. 
If the block xyz is a rail OR xyz + 1y is rail and xyz is block OR xyz - 1y is rail and xyz is air then it connects. xyz does not have to be a rail itself.

ἔρρωσο

> On Mar 30, 2022, at 16:32, sschr15 ***@***.***> wrote:
> 
> @sschr15 requested changes on this pull request.
> 
> PR blocked until this can be figured out
> what is better name for what the method does and where it's called
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2023-09-19 12:54 UTC, closed without merging